apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mineru-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-client # adjust for your cluster

